export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const LISTA_PRODUCTOS = 'LISTA_PRODUCTOS';
export const LISTA_PRODUCTOS_EXITO = 'LISTA_PRODUCTOS_EXITO';
export const LISTA_PRODUCTOS_ERROR = 'LISTA_PRODUCTOS_ERROR';

export const PRODUCTO_ELIMINAR = 'PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO = 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';

export const PRODUCTO_EDITAR = 'PRODUCTO_EDITAR';
export const PRODUCTO_EDITAR_EXITO = 'PRODUCTO_EDITAR_EXITO';
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';
export const PRODUCTO_EDITAR_INICIO = 'PRODUCTO_EDITAR_INICIO';

export const ALERTA_MOSTRAR = 'ALERTA_MOSTRAR';
export const ALERTA_OCULTAR = 'ALERTA_OCULTAR';